/**
* Payment Gateway
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.ccommercepayment.apis

import com.ccommercepayment.models.StoredPaymentMethodRequest
import com.ccommercepayment.models.StoredPaymentMethodResponse

import com.ccommercepayment.infrastructure.ApiClient
import com.ccommercepayment.infrastructure.ClientException
import com.ccommercepayment.infrastructure.ClientError
import com.ccommercepayment.infrastructure.ServerException
import com.ccommercepayment.infrastructure.ServerError
import com.ccommercepayment.infrastructure.MultiValueMap
import com.ccommercepayment.infrastructure.RequestConfig
import com.ccommercepayment.infrastructure.RequestMethod
import com.ccommercepayment.infrastructure.ResponseType
import com.ccommercepayment.infrastructure.Success
import com.ccommercepayment.infrastructure.toMultiValue

class StoredPaymentMethodsApi(basePath: kotlin.String = "http://localhost") : ApiClient(basePath) {

    /**
    * Gets stored payment methods by CustomerRef
    * Gets the stored payment methods by customer reference.
    * @param merchantId The merchant identifier. 
    * @param merchantSiteId The merchant site identifier. 
    * @param customerRef The customer reference. 
    * @param authToken Gets or sets the authentication token. 
    * @return StoredPaymentMethodResponse
    */
    @Suppress("UNCHECKED_CAST")
    fun v1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdCustomerRefByCustomerRefGet(merchantId: kotlin.Int, merchantSiteId: kotlin.String, customerRef: kotlin.String, authToken: kotlin.String) : StoredPaymentMethodResponse {
        val localVariableBody: kotlin.Any? = null
        val localVariableQuery: MultiValueMap = mapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf("authToken" to authToken.toString())
        val localVariableConfig = RequestConfig(
            RequestMethod.GET,
            "/v1/stored-payment-methods/merchants/{merchantId}/sites/{merchantSiteId}/customerRef/{customerRef}".replace("{"+"merchantId"+"}", "$merchantId").replace("{"+"merchantSiteId"+"}", "$merchantSiteId").replace("{"+"customerRef"+"}", "$customerRef"),
            query = localVariableQuery,
            headers = localVariableHeaders
        )
        val response = request<StoredPaymentMethodResponse>(
            localVariableConfig,
            localVariableBody
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as StoredPaymentMethodResponse
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }

    /**
    * Deletes a stored payment method
    * Deletes the specified stored payment method.
    * @param merchantId The merchant identifier 
    * @param merchantSiteId The merchant site identifier 
    * @param storedPaymentMethodId The stored payment method identifier 
    * @param authToken Gets or sets the authentication token. 
    * @return kotlin.String
    */
    @Suppress("UNCHECKED_CAST")
    fun v1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdStoredPaymentMethodIdByStoredPaymentMethodIdDelete(merchantId: kotlin.Int, merchantSiteId: kotlin.String, storedPaymentMethodId: kotlin.String, authToken: kotlin.String) : kotlin.String {
        val localVariableBody: kotlin.Any? = null
        val localVariableQuery: MultiValueMap = mapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf("authToken" to authToken.toString())
        val localVariableConfig = RequestConfig(
            RequestMethod.DELETE,
            "/v1/stored-payment-methods/merchants/{merchantId}/sites/{merchantSiteId}/storedPaymentMethodId/{storedPaymentMethodId}".replace("{"+"merchantId"+"}", "$merchantId").replace("{"+"merchantSiteId"+"}", "$merchantSiteId").replace("{"+"storedPaymentMethodId"+"}", "$storedPaymentMethodId"),
            query = localVariableQuery,
            headers = localVariableHeaders
        )
        val response = request<kotlin.String>(
            localVariableConfig,
            localVariableBody
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as kotlin.String
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }

    /**
    * Gets a stored payment method
    * Gets the stored payment method by its unique identifier.
    * @param merchantId  
    * @param merchantSiteId  
    * @param storedPaymentMethodId The stored payment method identifier. 
    * @param authToken Gets or sets the authentication token. 
    * @return StoredPaymentMethodResponse
    */
    @Suppress("UNCHECKED_CAST")
    fun v1StoredPaymentMethodsMerchantsByMerchantIdSitesByMerchantSiteIdStoredPaymentMethodIdByStoredPaymentMethodIdGet(merchantId: kotlin.Int, merchantSiteId: kotlin.String, storedPaymentMethodId: kotlin.String, authToken: kotlin.String) : StoredPaymentMethodResponse {
        val localVariableBody: kotlin.Any? = null
        val localVariableQuery: MultiValueMap = mapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf("authToken" to authToken.toString())
        val localVariableConfig = RequestConfig(
            RequestMethod.GET,
            "/v1/stored-payment-methods/merchants/{merchantId}/sites/{merchantSiteId}/storedPaymentMethodId/{storedPaymentMethodId}".replace("{"+"merchantId"+"}", "$merchantId").replace("{"+"merchantSiteId"+"}", "$merchantSiteId").replace("{"+"storedPaymentMethodId"+"}", "$storedPaymentMethodId"),
            query = localVariableQuery,
            headers = localVariableHeaders
        )
        val response = request<StoredPaymentMethodResponse>(
            localVariableConfig,
            localVariableBody
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as StoredPaymentMethodResponse
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }

    /**
    * Stores a new payment method.
    * 
    * @param authToken Gets or sets the authentication token. 
    * @param storedPaymentMethodRequest The payment method to store. (optional)
    * @return kotlin.String
    */
    @Suppress("UNCHECKED_CAST")
    fun v1StoredPaymentMethodsPost(authToken: kotlin.String, storedPaymentMethodRequest: StoredPaymentMethodRequest?) : kotlin.String {
        val localVariableBody: kotlin.Any? = storedPaymentMethodRequest
        val localVariableQuery: MultiValueMap = mapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf("authToken" to authToken.toString())
        val localVariableConfig = RequestConfig(
            RequestMethod.POST,
            "/v1/stored-payment-methods",
            query = localVariableQuery,
            headers = localVariableHeaders
        )
        val response = request<kotlin.String>(
            localVariableConfig,
            localVariableBody
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as kotlin.String
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }

}
