/**
* Payment Gateway
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.ccommercepayment.models


import com.squareup.moshi.Json
/**
 * All acquiring bank data
 * @param acquiringBankRef The acquiring bank reference
 * @param name The acquiring bank name
 * @param active Indicates if the acquiring bank is active or not
 */
data class AcquiringBank (
    /* The acquiring bank reference */
    @Json(name = "acquiringBankRef")
    val acquiringBankRef: kotlin.String? = null,
    /* The acquiring bank name */
    @Json(name = "name")
    val name: kotlin.String? = null,
    /* Indicates if the acquiring bank is active or not */
    @Json(name = "active")
    val active: kotlin.Boolean? = null
) {

}

