/**
* Payment Gateway
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.ccommercepayment.models


import com.squareup.moshi.Json
/**
 * The validate authentication request.
 * @param merchantId The merchant identifier
 * @param merchantSiteId The merchant site identifier
 * @param card3dsPaymentRequestId The payment session identifier (guid), use it for 3DS payment
 * @param orderRef The order reference linked to the schedule and transaction
 * @param orderTag The order tag is a label for the schedule
 */
data class Card3DsValidateAuthenticationRequest (
    /* The merchant identifier */
    @Json(name = "merchantId")
    val merchantId: kotlin.Int,
    /* The merchant site identifier */
    @Json(name = "merchantSiteId")
    val merchantSiteId: kotlin.String,
    /* The payment session identifier (guid), use it for 3DS payment */
    @Json(name = "card3dsPaymentRequestId")
    val card3dsPaymentRequestId: kotlin.String,
    /* The order reference linked to the schedule and transaction */
    @Json(name = "orderRef")
    val orderRef: kotlin.String,
    /* The order tag is a label for the schedule */
    @Json(name = "orderTag")
    val orderTag: kotlin.String? = null
) {

}

