/**
* Payment Gateway
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.ccommercepayment.models


import com.squareup.moshi.Json
/**
 * All card Data
 * @param cardOptionId The card option identifier
 * @param cardScheme The card type
 * @param expirationDate The card's expiration date
 * @param cardNumber The card number
 * @param securityNumber The Security number (CVV)
 * @param cardLabel The name of the card owner
 */
data class CardData (
    /* The card type */
    @Json(name = "cardScheme")
    val cardScheme: CardData.CardScheme,
    /* The card number */
    @Json(name = "cardNumber")
    val cardNumber: kotlin.String,
    /* The card option identifier */
    @Json(name = "cardOptionId")
    val cardOptionId: kotlin.Int? = null,
    /* The card's expiration date */
    @Json(name = "expirationDate")
    val expirationDate: kotlin.String? = null,
    /* The Security number (CVV) */
    @Json(name = "securityNumber")
    val securityNumber: kotlin.String? = null,
    /* The name of the card owner */
    @Json(name = "cardLabel")
    val cardLabel: kotlin.String? = null
) {

    /**
    * The card type
    * Values: none,cb,visa,masterCard,cdiscount,casino,cofinoga,amex,finaref,aurore,cdiscountCup,diners,exito,exitoFranquicia,payPal,banContact,pse,paylib
    */
    enum class CardScheme(val value: kotlin.String){
    
        @Json(name = "none")
        none("none"),
    
        @Json(name = "cb")
        cb("cb"),
    
        @Json(name = "visa")
        visa("visa"),
    
        @Json(name = "masterCard")
        masterCard("masterCard"),
    
        @Json(name = "cdiscount")
        cdiscount("cdiscount"),
    
        @Json(name = "casino")
        casino("casino"),
    
        @Json(name = "cofinoga")
        cofinoga("cofinoga"),
    
        @Json(name = "amex")
        amex("amex"),
    
        @Json(name = "finaref")
        finaref("finaref"),
    
        @Json(name = "aurore")
        aurore("aurore"),
    
        @Json(name = "cdiscount_Cup")
        cdiscountCup("cdiscount_Cup"),
    
        @Json(name = "diners")
        diners("diners"),
    
        @Json(name = "exito")
        exito("exito"),
    
        @Json(name = "exitoFranquicia")
        exitoFranquicia("exitoFranquicia"),
    
        @Json(name = "payPal")
        payPal("payPal"),
    
        @Json(name = "banContact")
        banContact("banContact"),
    
        @Json(name = "pse")
        pse("pse"),
    
        @Json(name = "paylib")
        paylib("paylib");
    
    }

}

