/**
* Payment Gateway
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.ccommercepayment.models


import com.squareup.moshi.Json
/**
 * The Copy Data (mandatory for author by copy)
 * @param fromOrderRef The order reference to use for the copy
 * @param fromOrderTag The order label to use for the copy
 */
data class CopyReference (
    /* The order reference to use for the copy */
    @Json(name = "fromOrderRef")
    val fromOrderRef: kotlin.String,
    /* The order label to use for the copy */
    @Json(name = "fromOrderTag")
    val fromOrderTag: kotlin.String? = null
) {

}

