/**
* Payment Gateway
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.ccommercepayment.models

import com.ccommercepayment.models.ShippingAddress

import com.squareup.moshi.Json
/**
 * Customer
 * @param billingAddress 
 * @param birthDate Gets or sets the birth date.
 * @param civility Gets or sets the civility.
 * @param country Gets or sets the country field.
 * @param customerIp Gets or sets the customer ip field.
 * @param customerRef Gets or sets the customer reference field.
 * @param deliveryAddress 
 * @param email Gets or sets the email.
 * @param firstName Gets or sets the first name.
 * @param lastName Gets or sets the last name.
 * @param mobilePhone Gets or sets the mobile phone.
 * @param phone Gets or sets the phone.
 */
data class Customer (
    @Json(name = "billingAddress")
    val billingAddress: ShippingAddress? = null,
    /* Gets or sets the birth date. */
    @Json(name = "birthDate")
    val birthDate: kotlin.String? = null,
    /* Gets or sets the civility. */
    @Json(name = "civility")
    val civility: Customer.Civility? = null,
    /* Gets or sets the country field. */
    @Json(name = "country")
    val country: Customer.Country? = null,
    /* Gets or sets the customer ip field. */
    @Json(name = "customerIp")
    val customerIp: kotlin.String? = null,
    /* Gets or sets the customer reference field. */
    @Json(name = "customerRef")
    val customerRef: kotlin.String? = null,
    @Json(name = "deliveryAddress")
    val deliveryAddress: ShippingAddress? = null,
    /* Gets or sets the email. */
    @Json(name = "email")
    val email: kotlin.String? = null,
    /* Gets or sets the first name. */
    @Json(name = "firstName")
    val firstName: kotlin.String? = null,
    /* Gets or sets the last name. */
    @Json(name = "lastName")
    val lastName: kotlin.String? = null,
    /* Gets or sets the mobile phone. */
    @Json(name = "mobilePhone")
    val mobilePhone: kotlin.String? = null,
    /* Gets or sets the phone. */
    @Json(name = "phone")
    val phone: kotlin.String? = null
) {

    /**
    * Gets or sets the civility.
    * Values: unknown,mister,misses,miss
    */
    enum class Civility(val value: kotlin.String){
    
        @Json(name = "unknown")
        unknown("unknown"),
    
        @Json(name = "mister")
        mister("mister"),
    
        @Json(name = "misses")
        misses("misses"),
    
        @Json(name = "miss")
        miss("miss");
    
    }

    /**
    * Gets or sets the country field.
    * Values: unknown,aw,af,ao,ai,al,ad,an,ae,ar,am,`as`,aq,tf,ag,au,at,az,bi,be,bj,bf,bd,bg,bh,bs,ba,by,bz,bm,bo,br,bb,bn,bt,bv,bw,cf,ca,cc,ch,cl,cn,ci,cm,cg,ck,co,km,cv,cr,cu,cx,ky,cy,cz,de,dj,dm,dk,`do`,dz,ec,eg,er,eh,es,ee,et,fi,fj,fk,fr,fo,fm,ga,gb,ge,gh,gi,gn,gp,gm,gw,gq,gr,gd,gl,gt,gf,gu,gy,hk,hm,hn,hr,ht,hu,id,`in`,io,ie,ir,iq,`is`,il,`it`,jm,jo,jp,kz,ke,kg,kh,ki,kn,kr,kw,la,lb,lr,ly,lc,li,lk,ls,lt,lu,lv,mo,ma,mc,md,mg,mv,mx,mh,mk,ml,mt,mm,mn,mp,mz,mr,ms,mq,mu,mw,my,yt,na,nc,ne,nf,ng,ni,nu,nl,no,np,nr,nz,om,pk,pa,pn,pe,ph,pw,pg,pl,pr,kp,pt,py,pf,qa,re,ro,ru,rw,sa,sd,sn,sg,gs,sh,sj,sb,sl,sv,sm,so,pm,st,sr,sk,si,se,sz,sc,sy,tc,td,tg,th,tj,tk,tm,tp,to,tt,tn,tr,tv,tw,tz,ug,ua,um,uy,us,uz,va,vc,ve,vg,vi,vn,vu,wf,ws,ye,za,zm,zw
    */
    enum class Country(val value: kotlin.String){
    
        @Json(name = "unknown")
        unknown("unknown"),
    
        @Json(name = "aw")
        aw("aw"),
    
        @Json(name = "af")
        af("af"),
    
        @Json(name = "ao")
        ao("ao"),
    
        @Json(name = "ai")
        ai("ai"),
    
        @Json(name = "al")
        al("al"),
    
        @Json(name = "ad")
        ad("ad"),
    
        @Json(name = "an")
        an("an"),
    
        @Json(name = "ae")
        ae("ae"),
    
        @Json(name = "ar")
        ar("ar"),
    
        @Json(name = "am")
        am("am"),
    
        @Json(name = "as")
        `as`("as"),
    
        @Json(name = "aq")
        aq("aq"),
    
        @Json(name = "tf")
        tf("tf"),
    
        @Json(name = "ag")
        ag("ag"),
    
        @Json(name = "au")
        au("au"),
    
        @Json(name = "at")
        at("at"),
    
        @Json(name = "az")
        az("az"),
    
        @Json(name = "bi")
        bi("bi"),
    
        @Json(name = "be")
        be("be"),
    
        @Json(name = "bj")
        bj("bj"),
    
        @Json(name = "bf")
        bf("bf"),
    
        @Json(name = "bd")
        bd("bd"),
    
        @Json(name = "bg")
        bg("bg"),
    
        @Json(name = "bh")
        bh("bh"),
    
        @Json(name = "bs")
        bs("bs"),
    
        @Json(name = "ba")
        ba("ba"),
    
        @Json(name = "by")
        by("by"),
    
        @Json(name = "bz")
        bz("bz"),
    
        @Json(name = "bm")
        bm("bm"),
    
        @Json(name = "bo")
        bo("bo"),
    
        @Json(name = "br")
        br("br"),
    
        @Json(name = "bb")
        bb("bb"),
    
        @Json(name = "bn")
        bn("bn"),
    
        @Json(name = "bt")
        bt("bt"),
    
        @Json(name = "bv")
        bv("bv"),
    
        @Json(name = "bw")
        bw("bw"),
    
        @Json(name = "cf")
        cf("cf"),
    
        @Json(name = "ca")
        ca("ca"),
    
        @Json(name = "cc")
        cc("cc"),
    
        @Json(name = "ch")
        ch("ch"),
    
        @Json(name = "cl")
        cl("cl"),
    
        @Json(name = "cn")
        cn("cn"),
    
        @Json(name = "ci")
        ci("ci"),
    
        @Json(name = "cm")
        cm("cm"),
    
        @Json(name = "cg")
        cg("cg"),
    
        @Json(name = "ck")
        ck("ck"),
    
        @Json(name = "co")
        co("co"),
    
        @Json(name = "km")
        km("km"),
    
        @Json(name = "cv")
        cv("cv"),
    
        @Json(name = "cr")
        cr("cr"),
    
        @Json(name = "cu")
        cu("cu"),
    
        @Json(name = "cx")
        cx("cx"),
    
        @Json(name = "ky")
        ky("ky"),
    
        @Json(name = "cy")
        cy("cy"),
    
        @Json(name = "cz")
        cz("cz"),
    
        @Json(name = "de")
        de("de"),
    
        @Json(name = "dj")
        dj("dj"),
    
        @Json(name = "dm")
        dm("dm"),
    
        @Json(name = "dk")
        dk("dk"),
    
        @Json(name = "do")
        `do`("do"),
    
        @Json(name = "dz")
        dz("dz"),
    
        @Json(name = "ec")
        ec("ec"),
    
        @Json(name = "eg")
        eg("eg"),
    
        @Json(name = "er")
        er("er"),
    
        @Json(name = "eh")
        eh("eh"),
    
        @Json(name = "es")
        es("es"),
    
        @Json(name = "ee")
        ee("ee"),
    
        @Json(name = "et")
        et("et"),
    
        @Json(name = "fi")
        fi("fi"),
    
        @Json(name = "fj")
        fj("fj"),
    
        @Json(name = "fk")
        fk("fk"),
    
        @Json(name = "fr")
        fr("fr"),
    
        @Json(name = "fo")
        fo("fo"),
    
        @Json(name = "fm")
        fm("fm"),
    
        @Json(name = "ga")
        ga("ga"),
    
        @Json(name = "gb")
        gb("gb"),
    
        @Json(name = "ge")
        ge("ge"),
    
        @Json(name = "gh")
        gh("gh"),
    
        @Json(name = "gi")
        gi("gi"),
    
        @Json(name = "gn")
        gn("gn"),
    
        @Json(name = "gp")
        gp("gp"),
    
        @Json(name = "gm")
        gm("gm"),
    
        @Json(name = "gw")
        gw("gw"),
    
        @Json(name = "gq")
        gq("gq"),
    
        @Json(name = "gr")
        gr("gr"),
    
        @Json(name = "gd")
        gd("gd"),
    
        @Json(name = "gl")
        gl("gl"),
    
        @Json(name = "gt")
        gt("gt"),
    
        @Json(name = "gf")
        gf("gf"),
    
        @Json(name = "gu")
        gu("gu"),
    
        @Json(name = "gy")
        gy("gy"),
    
        @Json(name = "hk")
        hk("hk"),
    
        @Json(name = "hm")
        hm("hm"),
    
        @Json(name = "hn")
        hn("hn"),
    
        @Json(name = "hr")
        hr("hr"),
    
        @Json(name = "ht")
        ht("ht"),
    
        @Json(name = "hu")
        hu("hu"),
    
        @Json(name = "id")
        id("id"),
    
        @Json(name = "in")
        `in`("in"),
    
        @Json(name = "io")
        io("io"),
    
        @Json(name = "ie")
        ie("ie"),
    
        @Json(name = "ir")
        ir("ir"),
    
        @Json(name = "iq")
        iq("iq"),
    
        @Json(name = "is")
        `is`("is"),
    
        @Json(name = "il")
        il("il"),
    
        @Json(name = "it")
        `it`("it"),
    
        @Json(name = "jm")
        jm("jm"),
    
        @Json(name = "jo")
        jo("jo"),
    
        @Json(name = "jp")
        jp("jp"),
    
        @Json(name = "kz")
        kz("kz"),
    
        @Json(name = "ke")
        ke("ke"),
    
        @Json(name = "kg")
        kg("kg"),
    
        @Json(name = "kh")
        kh("kh"),
    
        @Json(name = "ki")
        ki("ki"),
    
        @Json(name = "kn")
        kn("kn"),
    
        @Json(name = "kr")
        kr("kr"),
    
        @Json(name = "kw")
        kw("kw"),
    
        @Json(name = "la")
        la("la"),
    
        @Json(name = "lb")
        lb("lb"),
    
        @Json(name = "lr")
        lr("lr"),
    
        @Json(name = "ly")
        ly("ly"),
    
        @Json(name = "lc")
        lc("lc"),
    
        @Json(name = "li")
        li("li"),
    
        @Json(name = "lk")
        lk("lk"),
    
        @Json(name = "ls")
        ls("ls"),
    
        @Json(name = "lt")
        lt("lt"),
    
        @Json(name = "lu")
        lu("lu"),
    
        @Json(name = "lv")
        lv("lv"),
    
        @Json(name = "mo")
        mo("mo"),
    
        @Json(name = "ma")
        ma("ma"),
    
        @Json(name = "mc")
        mc("mc"),
    
        @Json(name = "md")
        md("md"),
    
        @Json(name = "mg")
        mg("mg"),
    
        @Json(name = "mv")
        mv("mv"),
    
        @Json(name = "mx")
        mx("mx"),
    
        @Json(name = "mh")
        mh("mh"),
    
        @Json(name = "mk")
        mk("mk"),
    
        @Json(name = "ml")
        ml("ml"),
    
        @Json(name = "mt")
        mt("mt"),
    
        @Json(name = "mm")
        mm("mm"),
    
        @Json(name = "mn")
        mn("mn"),
    
        @Json(name = "mp")
        mp("mp"),
    
        @Json(name = "mz")
        mz("mz"),
    
        @Json(name = "mr")
        mr("mr"),
    
        @Json(name = "ms")
        ms("ms"),
    
        @Json(name = "mq")
        mq("mq"),
    
        @Json(name = "mu")
        mu("mu"),
    
        @Json(name = "mw")
        mw("mw"),
    
        @Json(name = "my")
        my("my"),
    
        @Json(name = "yt")
        yt("yt"),
    
        @Json(name = "na")
        na("na"),
    
        @Json(name = "nc")
        nc("nc"),
    
        @Json(name = "ne")
        ne("ne"),
    
        @Json(name = "nf")
        nf("nf"),
    
        @Json(name = "ng")
        ng("ng"),
    
        @Json(name = "ni")
        ni("ni"),
    
        @Json(name = "nu")
        nu("nu"),
    
        @Json(name = "nl")
        nl("nl"),
    
        @Json(name = "no")
        no("no"),
    
        @Json(name = "np")
        np("np"),
    
        @Json(name = "nr")
        nr("nr"),
    
        @Json(name = "nz")
        nz("nz"),
    
        @Json(name = "om")
        om("om"),
    
        @Json(name = "pk")
        pk("pk"),
    
        @Json(name = "pa")
        pa("pa"),
    
        @Json(name = "pn")
        pn("pn"),
    
        @Json(name = "pe")
        pe("pe"),
    
        @Json(name = "ph")
        ph("ph"),
    
        @Json(name = "pw")
        pw("pw"),
    
        @Json(name = "pg")
        pg("pg"),
    
        @Json(name = "pl")
        pl("pl"),
    
        @Json(name = "pr")
        pr("pr"),
    
        @Json(name = "kp")
        kp("kp"),
    
        @Json(name = "pt")
        pt("pt"),
    
        @Json(name = "py")
        py("py"),
    
        @Json(name = "pf")
        pf("pf"),
    
        @Json(name = "qa")
        qa("qa"),
    
        @Json(name = "re")
        re("re"),
    
        @Json(name = "ro")
        ro("ro"),
    
        @Json(name = "ru")
        ru("ru"),
    
        @Json(name = "rw")
        rw("rw"),
    
        @Json(name = "sa")
        sa("sa"),
    
        @Json(name = "sd")
        sd("sd"),
    
        @Json(name = "sn")
        sn("sn"),
    
        @Json(name = "sg")
        sg("sg"),
    
        @Json(name = "gs")
        gs("gs"),
    
        @Json(name = "sh")
        sh("sh"),
    
        @Json(name = "sj")
        sj("sj"),
    
        @Json(name = "sb")
        sb("sb"),
    
        @Json(name = "sl")
        sl("sl"),
    
        @Json(name = "sv")
        sv("sv"),
    
        @Json(name = "sm")
        sm("sm"),
    
        @Json(name = "so")
        so("so"),
    
        @Json(name = "pm")
        pm("pm"),
    
        @Json(name = "st")
        st("st"),
    
        @Json(name = "sr")
        sr("sr"),
    
        @Json(name = "sk")
        sk("sk"),
    
        @Json(name = "si")
        si("si"),
    
        @Json(name = "se")
        se("se"),
    
        @Json(name = "sz")
        sz("sz"),
    
        @Json(name = "sc")
        sc("sc"),
    
        @Json(name = "sy")
        sy("sy"),
    
        @Json(name = "tc")
        tc("tc"),
    
        @Json(name = "td")
        td("td"),
    
        @Json(name = "tg")
        tg("tg"),
    
        @Json(name = "th")
        th("th"),
    
        @Json(name = "tj")
        tj("tj"),
    
        @Json(name = "tk")
        tk("tk"),
    
        @Json(name = "tm")
        tm("tm"),
    
        @Json(name = "tp")
        tp("tp"),
    
        @Json(name = "to")
        to("to"),
    
        @Json(name = "tt")
        tt("tt"),
    
        @Json(name = "tn")
        tn("tn"),
    
        @Json(name = "tr")
        tr("tr"),
    
        @Json(name = "tv")
        tv("tv"),
    
        @Json(name = "tw")
        tw("tw"),
    
        @Json(name = "tz")
        tz("tz"),
    
        @Json(name = "ug")
        ug("ug"),
    
        @Json(name = "ua")
        ua("ua"),
    
        @Json(name = "um")
        um("um"),
    
        @Json(name = "uy")
        uy("uy"),
    
        @Json(name = "us")
        us("us"),
    
        @Json(name = "uz")
        uz("uz"),
    
        @Json(name = "va")
        va("va"),
    
        @Json(name = "vc")
        vc("vc"),
    
        @Json(name = "ve")
        ve("ve"),
    
        @Json(name = "vg")
        vg("vg"),
    
        @Json(name = "vi")
        vi("vi"),
    
        @Json(name = "vn")
        vn("vn"),
    
        @Json(name = "vu")
        vu("vu"),
    
        @Json(name = "wf")
        wf("wf"),
    
        @Json(name = "ws")
        ws("ws"),
    
        @Json(name = "ye")
        ye("ye"),
    
        @Json(name = "za")
        za("za"),
    
        @Json(name = "zm")
        zm("zm"),
    
        @Json(name = "zw")
        zw("zw");
    
    }

}

