/**
* Payment Gateway
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.ccommercepayment.models

import com.ccommercepayment.models.DuplicatePaymentRequest

import com.squareup.moshi.Json
/**
 * The AuthorByCopy batch Payment Request
 * @param duplicatePaymentRequestList Gets or Sets ContextData
 */
data class DuplicatePaymentBatchRequest (
    /* Gets or Sets ContextData */
    @Json(name = "duplicatePaymentRequestList")
    val duplicatePaymentRequestList: kotlin.Array<DuplicatePaymentRequest>
) {

}

