/**
* Payment Gateway
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.ccommercepayment.models

import com.ccommercepayment.models.LoanTerm

import com.squareup.moshi.Json
/**
 * All loan offer data
 * @param loanRef The loan offer reference
 * @param loanTerms All loan terms data
 */
data class LoanOffer (
    /* The loan offer reference */
    @Json(name = "loanRef")
    val loanRef: kotlin.String? = null,
    /* All loan terms data */
    @Json(name = "loanTerms")
    val loanTerms: kotlin.Array<LoanTerm>? = null
) {

}

