/**
* Payment Gateway
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.ccommercepayment.models


import com.squareup.moshi.Json
/**
 * All loan term data
 * @param loanTermRef The loan term reference
 * @param minAmount The minimum amount allowed
 * @param maxAmount The maximum amount allowed
 * @param effectiveRate The effective rate
 * @param monthlyPayment The monthly payment
 * @param despositPercentage The desposit percentage
 * @param totalBillingCycles The total billing cycles
 * @param defaultTerm Indicates if the loan term is the default or not
 * @param startDate The start date
 * @param endDate The end date
 */
data class LoanTerm (
    /* The loan term reference */
    @Json(name = "loanTermRef")
    val loanTermRef: kotlin.String? = null,
    /* The minimum amount allowed */
    @Json(name = "minAmount")
    val minAmount: kotlin.Long? = null,
    /* The maximum amount allowed */
    @Json(name = "maxAmount")
    val maxAmount: kotlin.Long? = null,
    /* The effective rate */
    @Json(name = "effectiveRate")
    val effectiveRate: kotlin.Int? = null,
    /* The monthly payment */
    @Json(name = "monthlyPayment")
    val monthlyPayment: kotlin.Long? = null,
    /* The desposit percentage */
    @Json(name = "despositPercentage")
    val despositPercentage: kotlin.Int? = null,
    /* The total billing cycles */
    @Json(name = "totalBillingCycles")
    val totalBillingCycles: kotlin.Int? = null,
    /* Indicates if the loan term is the default or not */
    @Json(name = "defaultTerm")
    val defaultTerm: kotlin.Boolean? = null,
    /* The start date */
    @Json(name = "startDate")
    val startDate: kotlin.String? = null,
    /* The end date */
    @Json(name = "endDate")
    val endDate: kotlin.String? = null
) {

}

