/**
* Payment Gateway
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.ccommercepayment.models


import com.squareup.moshi.Json
/**
 * 
 * @param reportDelayInDays The report delay in days
 * @param allowCardStorage Allow card storage for the payment
 */
data class Options (
    /* The report delay in days */
    @Json(name = "reportDelayInDays")
    val reportDelayInDays: kotlin.Int? = null,
    /* Allow card storage for the payment */
    @Json(name = "allowCardStorage")
    val allowCardStorage: kotlin.Boolean? = null
) {

}

