/**
* Payment Gateway
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.ccommercepayment.models


import com.squareup.moshi.Json
/**
 * All Payment Operation data for the request
 * @param merchantId The merchant identifier
 * @param merchantSiteId The merchant site identifier.
 * @param attempt The number of attempts (useful for CAPTURE).
 * @param rank The rank concerned by the operation
 * @param amount The amount
 */
data class PaymentOperationsRequest (
    /* The merchant identifier */
    @Json(name = "merchantId")
    val merchantId: kotlin.Int,
    /* The merchant site identifier. */
    @Json(name = "merchantSiteId")
    val merchantSiteId: kotlin.String,
    /* The number of attempts (useful for CAPTURE). */
    @Json(name = "attempt")
    val attempt: kotlin.Int,
    /* The rank concerned by the operation */
    @Json(name = "rank")
    val rank: kotlin.Int,
    /* The amount */
    @Json(name = "amount")
    val amount: kotlin.Long? = null
) {

}

