/**
* Payment Gateway
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.ccommercepayment.models


import com.squareup.moshi.Json
/**
 * All context data needed
 * @param currency The currency of the order (ISO 4217)
 * @param country The code of the country (ISO 3166-1 alpha-2)
 * @param amount The amount
 */
data class PaymentOptionsContextData (
    /* The currency of the order (ISO 4217) */
    @Json(name = "currency")
    val currency: PaymentOptionsContextData.Currency,
    /* The code of the country (ISO 3166-1 alpha-2) */
    @Json(name = "country")
    val country: PaymentOptionsContextData.Country,
    /* The amount */
    @Json(name = "amount")
    val amount: kotlin.Long
) {

    /**
    * The currency of the order (ISO 4217)
    * Values: unknown,aed,afn,all,amd,ang,aoa,ars,aud,awg,azn,bam,bbd,bdt,bgn,bhd,bif,bmd,bnd,bob,bov,brl,bsd,btn,bwp,byr,bzd,cad,cdf,che,chf,chw,clf,clp,cny,cop,cou,crc,cuc,cup,cve,czk,djf,dkk,dop,dzd,egp,ern,etb,eur,fjd,fkp,gbp,gel,ghs,gip,gmd,gnf,gtq,gyd,hkd,hnl,hrk,htg,huf,idr,ils,inr,iqd,irr,isk,jmd,jod,jpy,kes,kgs,khr,kmf,kpw,krw,kwd,kyd,kzt,lak,lbp,lkr,lrd,lsl,lyd,mad,mdl,mga,mkd,mmk,mnt,mop,mro,mur,mvr,mwk,mxn,mxv,myr,mzn,nad,ngn,nio,nok,npr,nzd,omr,pab,pen,pgk,php,pkr,pln,pyg,qar,ron,rsd,rub,rwf,sar,sbd,scr,sdg,sek,sgd,shp,sll,sos,srd,ssp,std,svc,syp,szl,thb,tjs,tmt,tnd,top,`try`,ttd,twd,tzs,uah,ugx,usd,usn,uyi,uyu,uzs,vef,vnd,vuv,wst,xaf,xag,xau,xba,xbb,xbc,xbd,xcd,xdr,xof,xpd,xpf,xpt,xsu,xts,xua,xxx,yer,zar,zmw,zwl
    */
    enum class Currency(val value: kotlin.String){
    
        @Json(name = "unknown")
        unknown("unknown"),
    
        @Json(name = "aed")
        aed("aed"),
    
        @Json(name = "afn")
        afn("afn"),
    
        @Json(name = "all")
        all("all"),
    
        @Json(name = "amd")
        amd("amd"),
    
        @Json(name = "ang")
        ang("ang"),
    
        @Json(name = "aoa")
        aoa("aoa"),
    
        @Json(name = "ars")
        ars("ars"),
    
        @Json(name = "aud")
        aud("aud"),
    
        @Json(name = "awg")
        awg("awg"),
    
        @Json(name = "azn")
        azn("azn"),
    
        @Json(name = "bam")
        bam("bam"),
    
        @Json(name = "bbd")
        bbd("bbd"),
    
        @Json(name = "bdt")
        bdt("bdt"),
    
        @Json(name = "bgn")
        bgn("bgn"),
    
        @Json(name = "bhd")
        bhd("bhd"),
    
        @Json(name = "bif")
        bif("bif"),
    
        @Json(name = "bmd")
        bmd("bmd"),
    
        @Json(name = "bnd")
        bnd("bnd"),
    
        @Json(name = "bob")
        bob("bob"),
    
        @Json(name = "bov")
        bov("bov"),
    
        @Json(name = "brl")
        brl("brl"),
    
        @Json(name = "bsd")
        bsd("bsd"),
    
        @Json(name = "btn")
        btn("btn"),
    
        @Json(name = "bwp")
        bwp("bwp"),
    
        @Json(name = "byr")
        byr("byr"),
    
        @Json(name = "bzd")
        bzd("bzd"),
    
        @Json(name = "cad")
        cad("cad"),
    
        @Json(name = "cdf")
        cdf("cdf"),
    
        @Json(name = "che")
        che("che"),
    
        @Json(name = "chf")
        chf("chf"),
    
        @Json(name = "chw")
        chw("chw"),
    
        @Json(name = "clf")
        clf("clf"),
    
        @Json(name = "clp")
        clp("clp"),
    
        @Json(name = "cny")
        cny("cny"),
    
        @Json(name = "cop")
        cop("cop"),
    
        @Json(name = "cou")
        cou("cou"),
    
        @Json(name = "crc")
        crc("crc"),
    
        @Json(name = "cuc")
        cuc("cuc"),
    
        @Json(name = "cup")
        cup("cup"),
    
        @Json(name = "cve")
        cve("cve"),
    
        @Json(name = "czk")
        czk("czk"),
    
        @Json(name = "djf")
        djf("djf"),
    
        @Json(name = "dkk")
        dkk("dkk"),
    
        @Json(name = "dop")
        dop("dop"),
    
        @Json(name = "dzd")
        dzd("dzd"),
    
        @Json(name = "egp")
        egp("egp"),
    
        @Json(name = "ern")
        ern("ern"),
    
        @Json(name = "etb")
        etb("etb"),
    
        @Json(name = "eur")
        eur("eur"),
    
        @Json(name = "fjd")
        fjd("fjd"),
    
        @Json(name = "fkp")
        fkp("fkp"),
    
        @Json(name = "gbp")
        gbp("gbp"),
    
        @Json(name = "gel")
        gel("gel"),
    
        @Json(name = "ghs")
        ghs("ghs"),
    
        @Json(name = "gip")
        gip("gip"),
    
        @Json(name = "gmd")
        gmd("gmd"),
    
        @Json(name = "gnf")
        gnf("gnf"),
    
        @Json(name = "gtq")
        gtq("gtq"),
    
        @Json(name = "gyd")
        gyd("gyd"),
    
        @Json(name = "hkd")
        hkd("hkd"),
    
        @Json(name = "hnl")
        hnl("hnl"),
    
        @Json(name = "hrk")
        hrk("hrk"),
    
        @Json(name = "htg")
        htg("htg"),
    
        @Json(name = "huf")
        huf("huf"),
    
        @Json(name = "idr")
        idr("idr"),
    
        @Json(name = "ils")
        ils("ils"),
    
        @Json(name = "inr")
        inr("inr"),
    
        @Json(name = "iqd")
        iqd("iqd"),
    
        @Json(name = "irr")
        irr("irr"),
    
        @Json(name = "isk")
        isk("isk"),
    
        @Json(name = "jmd")
        jmd("jmd"),
    
        @Json(name = "jod")
        jod("jod"),
    
        @Json(name = "jpy")
        jpy("jpy"),
    
        @Json(name = "kes")
        kes("kes"),
    
        @Json(name = "kgs")
        kgs("kgs"),
    
        @Json(name = "khr")
        khr("khr"),
    
        @Json(name = "kmf")
        kmf("kmf"),
    
        @Json(name = "kpw")
        kpw("kpw"),
    
        @Json(name = "krw")
        krw("krw"),
    
        @Json(name = "kwd")
        kwd("kwd"),
    
        @Json(name = "kyd")
        kyd("kyd"),
    
        @Json(name = "kzt")
        kzt("kzt"),
    
        @Json(name = "lak")
        lak("lak"),
    
        @Json(name = "lbp")
        lbp("lbp"),
    
        @Json(name = "lkr")
        lkr("lkr"),
    
        @Json(name = "lrd")
        lrd("lrd"),
    
        @Json(name = "lsl")
        lsl("lsl"),
    
        @Json(name = "lyd")
        lyd("lyd"),
    
        @Json(name = "mad")
        mad("mad"),
    
        @Json(name = "mdl")
        mdl("mdl"),
    
        @Json(name = "mga")
        mga("mga"),
    
        @Json(name = "mkd")
        mkd("mkd"),
    
        @Json(name = "mmk")
        mmk("mmk"),
    
        @Json(name = "mnt")
        mnt("mnt"),
    
        @Json(name = "mop")
        mop("mop"),
    
        @Json(name = "mro")
        mro("mro"),
    
        @Json(name = "mur")
        mur("mur"),
    
        @Json(name = "mvr")
        mvr("mvr"),
    
        @Json(name = "mwk")
        mwk("mwk"),
    
        @Json(name = "mxn")
        mxn("mxn"),
    
        @Json(name = "mxv")
        mxv("mxv"),
    
        @Json(name = "myr")
        myr("myr"),
    
        @Json(name = "mzn")
        mzn("mzn"),
    
        @Json(name = "nad")
        nad("nad"),
    
        @Json(name = "ngn")
        ngn("ngn"),
    
        @Json(name = "nio")
        nio("nio"),
    
        @Json(name = "nok")
        nok("nok"),
    
        @Json(name = "npr")
        npr("npr"),
    
        @Json(name = "nzd")
        nzd("nzd"),
    
        @Json(name = "omr")
        omr("omr"),
    
        @Json(name = "pab")
        pab("pab"),
    
        @Json(name = "pen")
        pen("pen"),
    
        @Json(name = "pgk")
        pgk("pgk"),
    
        @Json(name = "php")
        php("php"),
    
        @Json(name = "pkr")
        pkr("pkr"),
    
        @Json(name = "pln")
        pln("pln"),
    
        @Json(name = "pyg")
        pyg("pyg"),
    
        @Json(name = "qar")
        qar("qar"),
    
        @Json(name = "ron")
        ron("ron"),
    
        @Json(name = "rsd")
        rsd("rsd"),
    
        @Json(name = "rub")
        rub("rub"),
    
        @Json(name = "rwf")
        rwf("rwf"),
    
        @Json(name = "sar")
        sar("sar"),
    
        @Json(name = "sbd")
        sbd("sbd"),
    
        @Json(name = "scr")
        scr("scr"),
    
        @Json(name = "sdg")
        sdg("sdg"),
    
        @Json(name = "sek")
        sek("sek"),
    
        @Json(name = "sgd")
        sgd("sgd"),
    
        @Json(name = "shp")
        shp("shp"),
    
        @Json(name = "sll")
        sll("sll"),
    
        @Json(name = "sos")
        sos("sos"),
    
        @Json(name = "srd")
        srd("srd"),
    
        @Json(name = "ssp")
        ssp("ssp"),
    
        @Json(name = "std")
        std("std"),
    
        @Json(name = "svc")
        svc("svc"),
    
        @Json(name = "syp")
        syp("syp"),
    
        @Json(name = "szl")
        szl("szl"),
    
        @Json(name = "thb")
        thb("thb"),
    
        @Json(name = "tjs")
        tjs("tjs"),
    
        @Json(name = "tmt")
        tmt("tmt"),
    
        @Json(name = "tnd")
        tnd("tnd"),
    
        @Json(name = "top")
        top("top"),
    
        @Json(name = "try")
        `try`("try"),
    
        @Json(name = "ttd")
        ttd("ttd"),
    
        @Json(name = "twd")
        twd("twd"),
    
        @Json(name = "tzs")
        tzs("tzs"),
    
        @Json(name = "uah")
        uah("uah"),
    
        @Json(name = "ugx")
        ugx("ugx"),
    
        @Json(name = "usd")
        usd("usd"),
    
        @Json(name = "usn")
        usn("usn"),
    
        @Json(name = "uyi")
        uyi("uyi"),
    
        @Json(name = "uyu")
        uyu("uyu"),
    
        @Json(name = "uzs")
        uzs("uzs"),
    
        @Json(name = "vef")
        vef("vef"),
    
        @Json(name = "vnd")
        vnd("vnd"),
    
        @Json(name = "vuv")
        vuv("vuv"),
    
        @Json(name = "wst")
        wst("wst"),
    
        @Json(name = "xaf")
        xaf("xaf"),
    
        @Json(name = "xag")
        xag("xag"),
    
        @Json(name = "xau")
        xau("xau"),
    
        @Json(name = "xba")
        xba("xba"),
    
        @Json(name = "xbb")
        xbb("xbb"),
    
        @Json(name = "xbc")
        xbc("xbc"),
    
        @Json(name = "xbd")
        xbd("xbd"),
    
        @Json(name = "xcd")
        xcd("xcd"),
    
        @Json(name = "xdr")
        xdr("xdr"),
    
        @Json(name = "xof")
        xof("xof"),
    
        @Json(name = "xpd")
        xpd("xpd"),
    
        @Json(name = "xpf")
        xpf("xpf"),
    
        @Json(name = "xpt")
        xpt("xpt"),
    
        @Json(name = "xsu")
        xsu("xsu"),
    
        @Json(name = "xts")
        xts("xts"),
    
        @Json(name = "xua")
        xua("xua"),
    
        @Json(name = "xxx")
        xxx("xxx"),
    
        @Json(name = "yer")
        yer("yer"),
    
        @Json(name = "zar")
        zar("zar"),
    
        @Json(name = "zmw")
        zmw("zmw"),
    
        @Json(name = "zwl")
        zwl("zwl");
    
    }

    /**
    * The code of the country (ISO 3166-1 alpha-2)
    * Values: unknown,aw,af,ao,ai,al,ad,an,ae,ar,am,`as`,aq,tf,ag,au,at,az,bi,be,bj,bf,bd,bg,bh,bs,ba,by,bz,bm,bo,br,bb,bn,bt,bv,bw,cf,ca,cc,ch,cl,cn,ci,cm,cg,ck,co,km,cv,cr,cu,cx,ky,cy,cz,de,dj,dm,dk,`do`,dz,ec,eg,er,eh,es,ee,et,fi,fj,fk,fr,fo,fm,ga,gb,ge,gh,gi,gn,gp,gm,gw,gq,gr,gd,gl,gt,gf,gu,gy,hk,hm,hn,hr,ht,hu,id,`in`,io,ie,ir,iq,`is`,il,`it`,jm,jo,jp,kz,ke,kg,kh,ki,kn,kr,kw,la,lb,lr,ly,lc,li,lk,ls,lt,lu,lv,mo,ma,mc,md,mg,mv,mx,mh,mk,ml,mt,mm,mn,mp,mz,mr,ms,mq,mu,mw,my,yt,na,nc,ne,nf,ng,ni,nu,nl,no,np,nr,nz,om,pk,pa,pn,pe,ph,pw,pg,pl,pr,kp,pt,py,pf,qa,re,ro,ru,rw,sa,sd,sn,sg,gs,sh,sj,sb,sl,sv,sm,so,pm,st,sr,sk,si,se,sz,sc,sy,tc,td,tg,th,tj,tk,tm,tp,to,tt,tn,tr,tv,tw,tz,ug,ua,um,uy,us,uz,va,vc,ve,vg,vi,vn,vu,wf,ws,ye,za,zm,zw
    */
    enum class Country(val value: kotlin.String){
    
        @Json(name = "unknown")
        unknown("unknown"),
    
        @Json(name = "aw")
        aw("aw"),
    
        @Json(name = "af")
        af("af"),
    
        @Json(name = "ao")
        ao("ao"),
    
        @Json(name = "ai")
        ai("ai"),
    
        @Json(name = "al")
        al("al"),
    
        @Json(name = "ad")
        ad("ad"),
    
        @Json(name = "an")
        an("an"),
    
        @Json(name = "ae")
        ae("ae"),
    
        @Json(name = "ar")
        ar("ar"),
    
        @Json(name = "am")
        am("am"),
    
        @Json(name = "as")
        `as`("as"),
    
        @Json(name = "aq")
        aq("aq"),
    
        @Json(name = "tf")
        tf("tf"),
    
        @Json(name = "ag")
        ag("ag"),
    
        @Json(name = "au")
        au("au"),
    
        @Json(name = "at")
        at("at"),
    
        @Json(name = "az")
        az("az"),
    
        @Json(name = "bi")
        bi("bi"),
    
        @Json(name = "be")
        be("be"),
    
        @Json(name = "bj")
        bj("bj"),
    
        @Json(name = "bf")
        bf("bf"),
    
        @Json(name = "bd")
        bd("bd"),
    
        @Json(name = "bg")
        bg("bg"),
    
        @Json(name = "bh")
        bh("bh"),
    
        @Json(name = "bs")
        bs("bs"),
    
        @Json(name = "ba")
        ba("ba"),
    
        @Json(name = "by")
        by("by"),
    
        @Json(name = "bz")
        bz("bz"),
    
        @Json(name = "bm")
        bm("bm"),
    
        @Json(name = "bo")
        bo("bo"),
    
        @Json(name = "br")
        br("br"),
    
        @Json(name = "bb")
        bb("bb"),
    
        @Json(name = "bn")
        bn("bn"),
    
        @Json(name = "bt")
        bt("bt"),
    
        @Json(name = "bv")
        bv("bv"),
    
        @Json(name = "bw")
        bw("bw"),
    
        @Json(name = "cf")
        cf("cf"),
    
        @Json(name = "ca")
        ca("ca"),
    
        @Json(name = "cc")
        cc("cc"),
    
        @Json(name = "ch")
        ch("ch"),
    
        @Json(name = "cl")
        cl("cl"),
    
        @Json(name = "cn")
        cn("cn"),
    
        @Json(name = "ci")
        ci("ci"),
    
        @Json(name = "cm")
        cm("cm"),
    
        @Json(name = "cg")
        cg("cg"),
    
        @Json(name = "ck")
        ck("ck"),
    
        @Json(name = "co")
        co("co"),
    
        @Json(name = "km")
        km("km"),
    
        @Json(name = "cv")
        cv("cv"),
    
        @Json(name = "cr")
        cr("cr"),
    
        @Json(name = "cu")
        cu("cu"),
    
        @Json(name = "cx")
        cx("cx"),
    
        @Json(name = "ky")
        ky("ky"),
    
        @Json(name = "cy")
        cy("cy"),
    
        @Json(name = "cz")
        cz("cz"),
    
        @Json(name = "de")
        de("de"),
    
        @Json(name = "dj")
        dj("dj"),
    
        @Json(name = "dm")
        dm("dm"),
    
        @Json(name = "dk")
        dk("dk"),
    
        @Json(name = "do")
        `do`("do"),
    
        @Json(name = "dz")
        dz("dz"),
    
        @Json(name = "ec")
        ec("ec"),
    
        @Json(name = "eg")
        eg("eg"),
    
        @Json(name = "er")
        er("er"),
    
        @Json(name = "eh")
        eh("eh"),
    
        @Json(name = "es")
        es("es"),
    
        @Json(name = "ee")
        ee("ee"),
    
        @Json(name = "et")
        et("et"),
    
        @Json(name = "fi")
        fi("fi"),
    
        @Json(name = "fj")
        fj("fj"),
    
        @Json(name = "fk")
        fk("fk"),
    
        @Json(name = "fr")
        fr("fr"),
    
        @Json(name = "fo")
        fo("fo"),
    
        @Json(name = "fm")
        fm("fm"),
    
        @Json(name = "ga")
        ga("ga"),
    
        @Json(name = "gb")
        gb("gb"),
    
        @Json(name = "ge")
        ge("ge"),
    
        @Json(name = "gh")
        gh("gh"),
    
        @Json(name = "gi")
        gi("gi"),
    
        @Json(name = "gn")
        gn("gn"),
    
        @Json(name = "gp")
        gp("gp"),
    
        @Json(name = "gm")
        gm("gm"),
    
        @Json(name = "gw")
        gw("gw"),
    
        @Json(name = "gq")
        gq("gq"),
    
        @Json(name = "gr")
        gr("gr"),
    
        @Json(name = "gd")
        gd("gd"),
    
        @Json(name = "gl")
        gl("gl"),
    
        @Json(name = "gt")
        gt("gt"),
    
        @Json(name = "gf")
        gf("gf"),
    
        @Json(name = "gu")
        gu("gu"),
    
        @Json(name = "gy")
        gy("gy"),
    
        @Json(name = "hk")
        hk("hk"),
    
        @Json(name = "hm")
        hm("hm"),
    
        @Json(name = "hn")
        hn("hn"),
    
        @Json(name = "hr")
        hr("hr"),
    
        @Json(name = "ht")
        ht("ht"),
    
        @Json(name = "hu")
        hu("hu"),
    
        @Json(name = "id")
        id("id"),
    
        @Json(name = "in")
        `in`("in"),
    
        @Json(name = "io")
        io("io"),
    
        @Json(name = "ie")
        ie("ie"),
    
        @Json(name = "ir")
        ir("ir"),
    
        @Json(name = "iq")
        iq("iq"),
    
        @Json(name = "is")
        `is`("is"),
    
        @Json(name = "il")
        il("il"),
    
        @Json(name = "it")
        `it`("it"),
    
        @Json(name = "jm")
        jm("jm"),
    
        @Json(name = "jo")
        jo("jo"),
    
        @Json(name = "jp")
        jp("jp"),
    
        @Json(name = "kz")
        kz("kz"),
    
        @Json(name = "ke")
        ke("ke"),
    
        @Json(name = "kg")
        kg("kg"),
    
        @Json(name = "kh")
        kh("kh"),
    
        @Json(name = "ki")
        ki("ki"),
    
        @Json(name = "kn")
        kn("kn"),
    
        @Json(name = "kr")
        kr("kr"),
    
        @Json(name = "kw")
        kw("kw"),
    
        @Json(name = "la")
        la("la"),
    
        @Json(name = "lb")
        lb("lb"),
    
        @Json(name = "lr")
        lr("lr"),
    
        @Json(name = "ly")
        ly("ly"),
    
        @Json(name = "lc")
        lc("lc"),
    
        @Json(name = "li")
        li("li"),
    
        @Json(name = "lk")
        lk("lk"),
    
        @Json(name = "ls")
        ls("ls"),
    
        @Json(name = "lt")
        lt("lt"),
    
        @Json(name = "lu")
        lu("lu"),
    
        @Json(name = "lv")
        lv("lv"),
    
        @Json(name = "mo")
        mo("mo"),
    
        @Json(name = "ma")
        ma("ma"),
    
        @Json(name = "mc")
        mc("mc"),
    
        @Json(name = "md")
        md("md"),
    
        @Json(name = "mg")
        mg("mg"),
    
        @Json(name = "mv")
        mv("mv"),
    
        @Json(name = "mx")
        mx("mx"),
    
        @Json(name = "mh")
        mh("mh"),
    
        @Json(name = "mk")
        mk("mk"),
    
        @Json(name = "ml")
        ml("ml"),
    
        @Json(name = "mt")
        mt("mt"),
    
        @Json(name = "mm")
        mm("mm"),
    
        @Json(name = "mn")
        mn("mn"),
    
        @Json(name = "mp")
        mp("mp"),
    
        @Json(name = "mz")
        mz("mz"),
    
        @Json(name = "mr")
        mr("mr"),
    
        @Json(name = "ms")
        ms("ms"),
    
        @Json(name = "mq")
        mq("mq"),
    
        @Json(name = "mu")
        mu("mu"),
    
        @Json(name = "mw")
        mw("mw"),
    
        @Json(name = "my")
        my("my"),
    
        @Json(name = "yt")
        yt("yt"),
    
        @Json(name = "na")
        na("na"),
    
        @Json(name = "nc")
        nc("nc"),
    
        @Json(name = "ne")
        ne("ne"),
    
        @Json(name = "nf")
        nf("nf"),
    
        @Json(name = "ng")
        ng("ng"),
    
        @Json(name = "ni")
        ni("ni"),
    
        @Json(name = "nu")
        nu("nu"),
    
        @Json(name = "nl")
        nl("nl"),
    
        @Json(name = "no")
        no("no"),
    
        @Json(name = "np")
        np("np"),
    
        @Json(name = "nr")
        nr("nr"),
    
        @Json(name = "nz")
        nz("nz"),
    
        @Json(name = "om")
        om("om"),
    
        @Json(name = "pk")
        pk("pk"),
    
        @Json(name = "pa")
        pa("pa"),
    
        @Json(name = "pn")
        pn("pn"),
    
        @Json(name = "pe")
        pe("pe"),
    
        @Json(name = "ph")
        ph("ph"),
    
        @Json(name = "pw")
        pw("pw"),
    
        @Json(name = "pg")
        pg("pg"),
    
        @Json(name = "pl")
        pl("pl"),
    
        @Json(name = "pr")
        pr("pr"),
    
        @Json(name = "kp")
        kp("kp"),
    
        @Json(name = "pt")
        pt("pt"),
    
        @Json(name = "py")
        py("py"),
    
        @Json(name = "pf")
        pf("pf"),
    
        @Json(name = "qa")
        qa("qa"),
    
        @Json(name = "re")
        re("re"),
    
        @Json(name = "ro")
        ro("ro"),
    
        @Json(name = "ru")
        ru("ru"),
    
        @Json(name = "rw")
        rw("rw"),
    
        @Json(name = "sa")
        sa("sa"),
    
        @Json(name = "sd")
        sd("sd"),
    
        @Json(name = "sn")
        sn("sn"),
    
        @Json(name = "sg")
        sg("sg"),
    
        @Json(name = "gs")
        gs("gs"),
    
        @Json(name = "sh")
        sh("sh"),
    
        @Json(name = "sj")
        sj("sj"),
    
        @Json(name = "sb")
        sb("sb"),
    
        @Json(name = "sl")
        sl("sl"),
    
        @Json(name = "sv")
        sv("sv"),
    
        @Json(name = "sm")
        sm("sm"),
    
        @Json(name = "so")
        so("so"),
    
        @Json(name = "pm")
        pm("pm"),
    
        @Json(name = "st")
        st("st"),
    
        @Json(name = "sr")
        sr("sr"),
    
        @Json(name = "sk")
        sk("sk"),
    
        @Json(name = "si")
        si("si"),
    
        @Json(name = "se")
        se("se"),
    
        @Json(name = "sz")
        sz("sz"),
    
        @Json(name = "sc")
        sc("sc"),
    
        @Json(name = "sy")
        sy("sy"),
    
        @Json(name = "tc")
        tc("tc"),
    
        @Json(name = "td")
        td("td"),
    
        @Json(name = "tg")
        tg("tg"),
    
        @Json(name = "th")
        th("th"),
    
        @Json(name = "tj")
        tj("tj"),
    
        @Json(name = "tk")
        tk("tk"),
    
        @Json(name = "tm")
        tm("tm"),
    
        @Json(name = "tp")
        tp("tp"),
    
        @Json(name = "to")
        to("to"),
    
        @Json(name = "tt")
        tt("tt"),
    
        @Json(name = "tn")
        tn("tn"),
    
        @Json(name = "tr")
        tr("tr"),
    
        @Json(name = "tv")
        tv("tv"),
    
        @Json(name = "tw")
        tw("tw"),
    
        @Json(name = "tz")
        tz("tz"),
    
        @Json(name = "ug")
        ug("ug"),
    
        @Json(name = "ua")
        ua("ua"),
    
        @Json(name = "um")
        um("um"),
    
        @Json(name = "uy")
        uy("uy"),
    
        @Json(name = "us")
        us("us"),
    
        @Json(name = "uz")
        uz("uz"),
    
        @Json(name = "va")
        va("va"),
    
        @Json(name = "vc")
        vc("vc"),
    
        @Json(name = "ve")
        ve("ve"),
    
        @Json(name = "vg")
        vg("vg"),
    
        @Json(name = "vi")
        vi("vi"),
    
        @Json(name = "vn")
        vn("vn"),
    
        @Json(name = "vu")
        vu("vu"),
    
        @Json(name = "wf")
        wf("wf"),
    
        @Json(name = "ws")
        ws("ws"),
    
        @Json(name = "ye")
        ye("ye"),
    
        @Json(name = "za")
        za("za"),
    
        @Json(name = "zm")
        zm("zm"),
    
        @Json(name = "zw")
        zw("zw");
    
    }

}

