/**
* Payment Gateway
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.ccommercepayment.models


import com.squareup.moshi.Json
/**
 * All payment fee data
 * @param minAmount The minimum amount allowed
 * @param maxAmount The maximum amount allowed
 * @param rate The rate
 * @param amount The amount
 * @param startDate The start date
 * @param endDate The end date
 * @param reportDelayMin The minimum report delay
 * @param reportDelayMax The maximum report delay
 */
data class PaymentFee (
    /* The minimum amount allowed */
    @Json(name = "minAmount")
    val minAmount: kotlin.Long? = null,
    /* The maximum amount allowed */
    @Json(name = "maxAmount")
    val maxAmount: kotlin.Long? = null,
    /* The rate */
    @Json(name = "rate")
    val rate: kotlin.Int? = null,
    /* The amount */
    @Json(name = "amount")
    val amount: kotlin.Long? = null,
    /* The start date */
    @Json(name = "startDate")
    val startDate: kotlin.String? = null,
    /* The end date */
    @Json(name = "endDate")
    val endDate: kotlin.String? = null,
    /* The minimum report delay */
    @Json(name = "reportDelayMin")
    val reportDelayMin: kotlin.Int? = null,
    /* The maximum report delay */
    @Json(name = "reportDelayMax")
    val reportDelayMax: kotlin.Int? = null
) {

}

