/**
* Payment Gateway
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.ccommercepayment.models


import com.squareup.moshi.Json
/**
 * All payment schedule data
 * @param rank The rank
 * @param name The amount distribution weight
 * @param dateDelay The date delay
 * @param isBondRank Indicates if the rank is bonded or not
 * @param thresholdDay The threshold day
 * @param firstDueDay The first due day
 * @param firstDueMonthDelay The first due month delay
 * @param secondDueDay The second due day
 * @param secondDueMonthDelay The second due month delay
 * @param hasFees Indicates if the schedule rule has fees or not
 */
data class PaymentScheduleRule (
    /* The rank */
    @Json(name = "rank")
    val rank: kotlin.Int? = null,
    /* The amount distribution weight */
    @Json(name = "name")
    val name: kotlin.Int? = null,
    /* The date delay */
    @Json(name = "dateDelay")
    val dateDelay: kotlin.Int? = null,
    /* Indicates if the rank is bonded or not */
    @Json(name = "isBondRank")
    val isBondRank: kotlin.Boolean? = null,
    /* The threshold day */
    @Json(name = "thresholdDay")
    val thresholdDay: kotlin.Int? = null,
    /* The first due day */
    @Json(name = "firstDueDay")
    val firstDueDay: kotlin.Int? = null,
    /* The first due month delay */
    @Json(name = "firstDueMonthDelay")
    val firstDueMonthDelay: kotlin.Int? = null,
    /* The second due day */
    @Json(name = "secondDueDay")
    val secondDueDay: kotlin.Int? = null,
    /* The second due month delay */
    @Json(name = "secondDueMonthDelay")
    val secondDueMonthDelay: kotlin.Int? = null,
    /* Indicates if the schedule rule has fees or not */
    @Json(name = "hasFees")
    val hasFees: kotlin.Boolean? = null
) {

}

