/**
* Payment Gateway
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.ccommercepayment.models


import com.squareup.moshi.Json
/**
 * All schedule data
 * @param amount Gets or Sets Amount
 * @param date Gets or Sets Date
 * @param rank Gets or Sets Rank
 * @param currency Gets or Sets Currency
 * @param state State of the schedule
 * @param capturedAmount Gets or Sets CapturedAmount
 * @param remainingAmount Gets or Sets RemainingAmount
 * @param cancelledAmount Gets or Sets CancelledAmount
 * @param refundedAmount Gets or Sets RefundedAmount
 */
data class Schedule (
    /* Gets or Sets Amount */
    @Json(name = "amount")
    val amount: kotlin.Long? = null,
    /* Gets or Sets Date */
    @Json(name = "date")
    val date: kotlin.String? = null,
    /* Gets or Sets Rank */
    @Json(name = "rank")
    val rank: kotlin.Int? = null,
    /* Gets or Sets Currency */
    @Json(name = "currency")
    val currency: Schedule.Currency? = null,
    /* State of the schedule */
    @Json(name = "state")
    val state: Schedule.State? = null,
    /* Gets or Sets CapturedAmount */
    @Json(name = "capturedAmount")
    val capturedAmount: kotlin.Long? = null,
    /* Gets or Sets RemainingAmount */
    @Json(name = "remainingAmount")
    val remainingAmount: kotlin.Long? = null,
    /* Gets or Sets CancelledAmount */
    @Json(name = "cancelledAmount")
    val cancelledAmount: kotlin.Long? = null,
    /* Gets or Sets RefundedAmount */
    @Json(name = "refundedAmount")
    val refundedAmount: kotlin.Long? = null
) {

    /**
    * Gets or Sets Currency
    * Values: unknown,aed,afn,all,amd,ang,aoa,ars,aud,awg,azn,bam,bbd,bdt,bgn,bhd,bif,bmd,bnd,bob,bov,brl,bsd,btn,bwp,byr,bzd,cad,cdf,che,chf,chw,clf,clp,cny,cop,cou,crc,cuc,cup,cve,czk,djf,dkk,dop,dzd,egp,ern,etb,eur,fjd,fkp,gbp,gel,ghs,gip,gmd,gnf,gtq,gyd,hkd,hnl,hrk,htg,huf,idr,ils,inr,iqd,irr,isk,jmd,jod,jpy,kes,kgs,khr,kmf,kpw,krw,kwd,kyd,kzt,lak,lbp,lkr,lrd,lsl,lyd,mad,mdl,mga,mkd,mmk,mnt,mop,mro,mur,mvr,mwk,mxn,mxv,myr,mzn,nad,ngn,nio,nok,npr,nzd,omr,pab,pen,pgk,php,pkr,pln,pyg,qar,ron,rsd,rub,rwf,sar,sbd,scr,sdg,sek,sgd,shp,sll,sos,srd,ssp,std,svc,syp,szl,thb,tjs,tmt,tnd,top,`try`,ttd,twd,tzs,uah,ugx,usd,usn,uyi,uyu,uzs,vef,vnd,vuv,wst,xaf,xag,xau,xba,xbb,xbc,xbd,xcd,xdr,xof,xpd,xpf,xpt,xsu,xts,xua,xxx,yer,zar,zmw,zwl
    */
    enum class Currency(val value: kotlin.String){
    
        @Json(name = "unknown")
        unknown("unknown"),
    
        @Json(name = "aed")
        aed("aed"),
    
        @Json(name = "afn")
        afn("afn"),
    
        @Json(name = "all")
        all("all"),
    
        @Json(name = "amd")
        amd("amd"),
    
        @Json(name = "ang")
        ang("ang"),
    
        @Json(name = "aoa")
        aoa("aoa"),
    
        @Json(name = "ars")
        ars("ars"),
    
        @Json(name = "aud")
        aud("aud"),
    
        @Json(name = "awg")
        awg("awg"),
    
        @Json(name = "azn")
        azn("azn"),
    
        @Json(name = "bam")
        bam("bam"),
    
        @Json(name = "bbd")
        bbd("bbd"),
    
        @Json(name = "bdt")
        bdt("bdt"),
    
        @Json(name = "bgn")
        bgn("bgn"),
    
        @Json(name = "bhd")
        bhd("bhd"),
    
        @Json(name = "bif")
        bif("bif"),
    
        @Json(name = "bmd")
        bmd("bmd"),
    
        @Json(name = "bnd")
        bnd("bnd"),
    
        @Json(name = "bob")
        bob("bob"),
    
        @Json(name = "bov")
        bov("bov"),
    
        @Json(name = "brl")
        brl("brl"),
    
        @Json(name = "bsd")
        bsd("bsd"),
    
        @Json(name = "btn")
        btn("btn"),
    
        @Json(name = "bwp")
        bwp("bwp"),
    
        @Json(name = "byr")
        byr("byr"),
    
        @Json(name = "bzd")
        bzd("bzd"),
    
        @Json(name = "cad")
        cad("cad"),
    
        @Json(name = "cdf")
        cdf("cdf"),
    
        @Json(name = "che")
        che("che"),
    
        @Json(name = "chf")
        chf("chf"),
    
        @Json(name = "chw")
        chw("chw"),
    
        @Json(name = "clf")
        clf("clf"),
    
        @Json(name = "clp")
        clp("clp"),
    
        @Json(name = "cny")
        cny("cny"),
    
        @Json(name = "cop")
        cop("cop"),
    
        @Json(name = "cou")
        cou("cou"),
    
        @Json(name = "crc")
        crc("crc"),
    
        @Json(name = "cuc")
        cuc("cuc"),
    
        @Json(name = "cup")
        cup("cup"),
    
        @Json(name = "cve")
        cve("cve"),
    
        @Json(name = "czk")
        czk("czk"),
    
        @Json(name = "djf")
        djf("djf"),
    
        @Json(name = "dkk")
        dkk("dkk"),
    
        @Json(name = "dop")
        dop("dop"),
    
        @Json(name = "dzd")
        dzd("dzd"),
    
        @Json(name = "egp")
        egp("egp"),
    
        @Json(name = "ern")
        ern("ern"),
    
        @Json(name = "etb")
        etb("etb"),
    
        @Json(name = "eur")
        eur("eur"),
    
        @Json(name = "fjd")
        fjd("fjd"),
    
        @Json(name = "fkp")
        fkp("fkp"),
    
        @Json(name = "gbp")
        gbp("gbp"),
    
        @Json(name = "gel")
        gel("gel"),
    
        @Json(name = "ghs")
        ghs("ghs"),
    
        @Json(name = "gip")
        gip("gip"),
    
        @Json(name = "gmd")
        gmd("gmd"),
    
        @Json(name = "gnf")
        gnf("gnf"),
    
        @Json(name = "gtq")
        gtq("gtq"),
    
        @Json(name = "gyd")
        gyd("gyd"),
    
        @Json(name = "hkd")
        hkd("hkd"),
    
        @Json(name = "hnl")
        hnl("hnl"),
    
        @Json(name = "hrk")
        hrk("hrk"),
    
        @Json(name = "htg")
        htg("htg"),
    
        @Json(name = "huf")
        huf("huf"),
    
        @Json(name = "idr")
        idr("idr"),
    
        @Json(name = "ils")
        ils("ils"),
    
        @Json(name = "inr")
        inr("inr"),
    
        @Json(name = "iqd")
        iqd("iqd"),
    
        @Json(name = "irr")
        irr("irr"),
    
        @Json(name = "isk")
        isk("isk"),
    
        @Json(name = "jmd")
        jmd("jmd"),
    
        @Json(name = "jod")
        jod("jod"),
    
        @Json(name = "jpy")
        jpy("jpy"),
    
        @Json(name = "kes")
        kes("kes"),
    
        @Json(name = "kgs")
        kgs("kgs"),
    
        @Json(name = "khr")
        khr("khr"),
    
        @Json(name = "kmf")
        kmf("kmf"),
    
        @Json(name = "kpw")
        kpw("kpw"),
    
        @Json(name = "krw")
        krw("krw"),
    
        @Json(name = "kwd")
        kwd("kwd"),
    
        @Json(name = "kyd")
        kyd("kyd"),
    
        @Json(name = "kzt")
        kzt("kzt"),
    
        @Json(name = "lak")
        lak("lak"),
    
        @Json(name = "lbp")
        lbp("lbp"),
    
        @Json(name = "lkr")
        lkr("lkr"),
    
        @Json(name = "lrd")
        lrd("lrd"),
    
        @Json(name = "lsl")
        lsl("lsl"),
    
        @Json(name = "lyd")
        lyd("lyd"),
    
        @Json(name = "mad")
        mad("mad"),
    
        @Json(name = "mdl")
        mdl("mdl"),
    
        @Json(name = "mga")
        mga("mga"),
    
        @Json(name = "mkd")
        mkd("mkd"),
    
        @Json(name = "mmk")
        mmk("mmk"),
    
        @Json(name = "mnt")
        mnt("mnt"),
    
        @Json(name = "mop")
        mop("mop"),
    
        @Json(name = "mro")
        mro("mro"),
    
        @Json(name = "mur")
        mur("mur"),
    
        @Json(name = "mvr")
        mvr("mvr"),
    
        @Json(name = "mwk")
        mwk("mwk"),
    
        @Json(name = "mxn")
        mxn("mxn"),
    
        @Json(name = "mxv")
        mxv("mxv"),
    
        @Json(name = "myr")
        myr("myr"),
    
        @Json(name = "mzn")
        mzn("mzn"),
    
        @Json(name = "nad")
        nad("nad"),
    
        @Json(name = "ngn")
        ngn("ngn"),
    
        @Json(name = "nio")
        nio("nio"),
    
        @Json(name = "nok")
        nok("nok"),
    
        @Json(name = "npr")
        npr("npr"),
    
        @Json(name = "nzd")
        nzd("nzd"),
    
        @Json(name = "omr")
        omr("omr"),
    
        @Json(name = "pab")
        pab("pab"),
    
        @Json(name = "pen")
        pen("pen"),
    
        @Json(name = "pgk")
        pgk("pgk"),
    
        @Json(name = "php")
        php("php"),
    
        @Json(name = "pkr")
        pkr("pkr"),
    
        @Json(name = "pln")
        pln("pln"),
    
        @Json(name = "pyg")
        pyg("pyg"),
    
        @Json(name = "qar")
        qar("qar"),
    
        @Json(name = "ron")
        ron("ron"),
    
        @Json(name = "rsd")
        rsd("rsd"),
    
        @Json(name = "rub")
        rub("rub"),
    
        @Json(name = "rwf")
        rwf("rwf"),
    
        @Json(name = "sar")
        sar("sar"),
    
        @Json(name = "sbd")
        sbd("sbd"),
    
        @Json(name = "scr")
        scr("scr"),
    
        @Json(name = "sdg")
        sdg("sdg"),
    
        @Json(name = "sek")
        sek("sek"),
    
        @Json(name = "sgd")
        sgd("sgd"),
    
        @Json(name = "shp")
        shp("shp"),
    
        @Json(name = "sll")
        sll("sll"),
    
        @Json(name = "sos")
        sos("sos"),
    
        @Json(name = "srd")
        srd("srd"),
    
        @Json(name = "ssp")
        ssp("ssp"),
    
        @Json(name = "std")
        std("std"),
    
        @Json(name = "svc")
        svc("svc"),
    
        @Json(name = "syp")
        syp("syp"),
    
        @Json(name = "szl")
        szl("szl"),
    
        @Json(name = "thb")
        thb("thb"),
    
        @Json(name = "tjs")
        tjs("tjs"),
    
        @Json(name = "tmt")
        tmt("tmt"),
    
        @Json(name = "tnd")
        tnd("tnd"),
    
        @Json(name = "top")
        top("top"),
    
        @Json(name = "try")
        `try`("try"),
    
        @Json(name = "ttd")
        ttd("ttd"),
    
        @Json(name = "twd")
        twd("twd"),
    
        @Json(name = "tzs")
        tzs("tzs"),
    
        @Json(name = "uah")
        uah("uah"),
    
        @Json(name = "ugx")
        ugx("ugx"),
    
        @Json(name = "usd")
        usd("usd"),
    
        @Json(name = "usn")
        usn("usn"),
    
        @Json(name = "uyi")
        uyi("uyi"),
    
        @Json(name = "uyu")
        uyu("uyu"),
    
        @Json(name = "uzs")
        uzs("uzs"),
    
        @Json(name = "vef")
        vef("vef"),
    
        @Json(name = "vnd")
        vnd("vnd"),
    
        @Json(name = "vuv")
        vuv("vuv"),
    
        @Json(name = "wst")
        wst("wst"),
    
        @Json(name = "xaf")
        xaf("xaf"),
    
        @Json(name = "xag")
        xag("xag"),
    
        @Json(name = "xau")
        xau("xau"),
    
        @Json(name = "xba")
        xba("xba"),
    
        @Json(name = "xbb")
        xbb("xbb"),
    
        @Json(name = "xbc")
        xbc("xbc"),
    
        @Json(name = "xbd")
        xbd("xbd"),
    
        @Json(name = "xcd")
        xcd("xcd"),
    
        @Json(name = "xdr")
        xdr("xdr"),
    
        @Json(name = "xof")
        xof("xof"),
    
        @Json(name = "xpd")
        xpd("xpd"),
    
        @Json(name = "xpf")
        xpf("xpf"),
    
        @Json(name = "xpt")
        xpt("xpt"),
    
        @Json(name = "xsu")
        xsu("xsu"),
    
        @Json(name = "xts")
        xts("xts"),
    
        @Json(name = "xua")
        xua("xua"),
    
        @Json(name = "xxx")
        xxx("xxx"),
    
        @Json(name = "yer")
        yer("yer"),
    
        @Json(name = "zar")
        zar("zar"),
    
        @Json(name = "zmw")
        zmw("zmw"),
    
        @Json(name = "zwl")
        zwl("zwl");
    
    }

    /**
    * State of the schedule
    * Values: `init`,inPayment,payed,confirmed,refused,cancelled,pending,undetermined,discarded,cashing,cashed
    */
    enum class State(val value: kotlin.String){
    
        @Json(name = "init")
        `init`("init"),
    
        @Json(name = "inPayment")
        inPayment("inPayment"),
    
        @Json(name = "payed")
        payed("payed"),
    
        @Json(name = "confirmed")
        confirmed("confirmed"),
    
        @Json(name = "refused")
        refused("refused"),
    
        @Json(name = "cancelled")
        cancelled("cancelled"),
    
        @Json(name = "pending")
        pending("pending"),
    
        @Json(name = "undetermined")
        undetermined("undetermined"),
    
        @Json(name = "discarded")
        discarded("discarded"),
    
        @Json(name = "cashing")
        cashing("cashing"),
    
        @Json(name = "cashed")
        cashed("cashed");
    
    }

}

