/**
* Payment Gateway
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.ccommercepayment.models


import com.squareup.moshi.Json
/**
 * 
 * @param city Gets or sets the city field.
 * @param line1 Gets or sets the line1 field.
 * @param line2 Gets or sets the line2 field.
 * @param name Gets or sets the name field.
 * @param placeCalled Gets or sets the place called field.
 * @param zipCode Gets or sets the zip code field.
 */
data class ShippingAddress (
    /* Gets or sets the city field. */
    @Json(name = "city")
    val city: kotlin.String? = null,
    /* Gets or sets the line1 field. */
    @Json(name = "line1")
    val line1: kotlin.String? = null,
    /* Gets or sets the line2 field. */
    @Json(name = "line2")
    val line2: kotlin.String? = null,
    /* Gets or sets the name field. */
    @Json(name = "name")
    val name: kotlin.String? = null,
    /* Gets or sets the place called field. */
    @Json(name = "placeCalled")
    val placeCalled: kotlin.String? = null,
    /* Gets or sets the zip code field. */
    @Json(name = "zipCode")
    val zipCode: kotlin.String? = null
) {

}

