/**
* Payment Gateway
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.ccommercepayment.models

import com.ccommercepayment.models.StoredPaymentMethod

import com.squareup.moshi.Json
/**
 * 
 * @param storedPaymentMethodList Gets or sets the stored payment method list.
 * @param responseMessage The global response message
 */
data class StoredPaymentMethodResponse (
    /* Gets or sets the stored payment method list. */
    @Json(name = "storedPaymentMethodList")
    val storedPaymentMethodList: kotlin.Array<StoredPaymentMethod>? = null,
    /* The global response message */
    @Json(name = "responseMessage")
    val responseMessage: kotlin.String? = null
) {

}

