/**
* Payment Gateway
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.ccommercepayment.models


import com.squareup.moshi.Json
/**
 * SubOrder
 * @param amount Gets or sets the amount field.
 * @param invoiceId Gets or sets the invoice identifier field.
 * @param orderAmountWithoutTax Gets or sets the order amount without tax field.
 * @param orderRef Gets or sets the order reference field.
 * @param taxAmount Gets or sets the tax amount field.
 */
data class SubOrder (
    /* Gets or sets the amount field. */
    @Json(name = "amount")
    val amount: kotlin.Long? = null,
    /* Gets or sets the invoice identifier field. */
    @Json(name = "invoiceId")
    val invoiceId: kotlin.String? = null,
    /* Gets or sets the order amount without tax field. */
    @Json(name = "orderAmountWithoutTax")
    val orderAmountWithoutTax: kotlin.Long? = null,
    /* Gets or sets the order reference field. */
    @Json(name = "orderRef")
    val orderRef: kotlin.String? = null,
    /* Gets or sets the tax amount field. */
    @Json(name = "taxAmount")
    val taxAmount: kotlin.Long? = null
) {

}

