/**
* Payment Gateway
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.ccommercepayment.models


import com.squareup.moshi.Json
/**
 * All ValidationMode Overriden data
 * @param captureDelay The delay capture overriden
 * @param validationMode The validation mode
 */
data class ValidationModeOverride (
    /* The validation mode */
    @Json(name = "validationMode")
    val validationMode: ValidationModeOverride.ValidationMode,
    /* The delay capture overriden */
    @Json(name = "captureDelay")
    val captureDelay: kotlin.Int? = null
) {

    /**
    * The validation mode
    * Values: undefined,auto,manual
    */
    enum class ValidationMode(val value: kotlin.String){
    
        @Json(name = "undefined")
        undefined("undefined"),
    
        @Json(name = "auto")
        auto("auto"),
    
        @Json(name = "manual")
        manual("manual");
    
    }

}

